--- #YAML:1.0
name:               Test-Bitcoin-Daemon
version:            0.02
abstract:           Test RPC commands against a temporary instance of bitcoind
author:
    - Jean-Pierre Rupp <root@xeno-genesis.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Which:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
